"""
export.py – Excel / KMZ export endpoints (Sites, Cells 3G/4G/5G, Antennas)

Scope of a Sites / Cells export:
  1. `ids` given   -> exactly those rows (the user's selection); other filters ignored
  2. otherwise     -> top-bar filters + column filters (`filters` JSON) [+ sort]

Every Sites / Cells endpoint comes in two flavours:
  GET  /export/<x>  query-string (legacy links; token via Bearer header OR ?token=)
  POST /export/<x>  JSON body {ids, filters, params, sort_by, sort_dir}
                    (needed because a selection can hold thousands of ids)
"""
from __future__ import annotations

import io
from functools import partial
from typing import Any, Callable, Dict, List, Optional

import openpyxl
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from fastapi import APIRouter, Depends, Query, HTTPException, Request
from fastapi.responses import StreamingResponse
from fastapi.security import OAuth2PasswordBearer
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.models.site import Site
from app.models.cell_3g import Cell3G
from app.models.cell_4g import Cell4G
from app.models.cell_5g import Cell5G
from app.models.antenna import Antenna
from app.models.user import User
from app.core.security import decode_access_token
from app.services.list_query import build_export_query
from app.services import kmz_export

router = APIRouter()

HEADER_FILL = PatternFill("solid", fgColor="1F4E79")
HEADER_FONT = Font(color="FFFFFF", bold=True, size=10)
CENTER      = Alignment(horizontal="center", vertical="center", wrap_text=True)
LEFT        = Alignment(horizontal="left",   vertical="center")
THIN        = Side(style="thin", color="D0D0D0")
BORDER      = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
ALT_FILL    = PatternFill("solid", fgColor="EBF3FB")

_EXPOSE = "X-Row-Count, X-Site-Count, X-Valid-Coords, Content-Disposition"


# ── auth: Bearer header OR ?token= ────────────────────────────────────────────
oauth2_optional = OAuth2PasswordBearer(tokenUrl="/api/v1/auth/login", auto_error=False)


def get_optional_user(
    token_header: Optional[str] = Depends(oauth2_optional),
    token_param:  Optional[str] = Query(None, alias="token"),
    db: Session = Depends(get_db),
) -> User:
    raw = token_header or token_param
    if not raw:
        raise HTTPException(status_code=401, detail="Not authenticated")
    payload = decode_access_token(raw)
    if not payload:
        raise HTTPException(status_code=401, detail="Invalid token")
    user = db.query(User).filter(User.username == payload.get("sub")).first()
    if not user or not user.is_active:
        raise HTTPException(status_code=401, detail="User inactive")
    return user


# ── workbook helpers ──────────────────────────────────────────────────────────
def _make_wb(headers):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.row_dimensions[1].height = 30
    ws.freeze_panes = "A2"
    for col_idx, (header, width) in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.fill = HEADER_FILL; cell.font = HEADER_FONT
        cell.alignment = CENTER; cell.border = BORDER
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    return wb, ws


def _style_row(ws, row_idx, num_cols, alternate):
    fill = ALT_FILL if alternate else None
    for col_idx in range(1, num_cols + 1):
        cell = ws.cell(row=row_idx, column=col_idx)
        cell.alignment = LEFT; cell.border = BORDER
        if fill: cell.fill = fill


def _stream(wb, filename, row_count=None):
    buf = io.BytesIO()
    wb.save(buf); buf.seek(0)
    headers = {
        "Content-Disposition": f'attachment; filename="{filename}"',
        "Access-Control-Expose-Headers": _EXPOSE,
    }
    if row_count is not None:
        headers["X-Row-Count"] = str(row_count)
    return StreamingResponse(
        iter([buf.read()]),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers=headers,
    )


def _safe_bool_export(v) -> bool:
    if v is None: return False
    if isinstance(v, bool): return v
    if isinstance(v, int): return v != 0
    if isinstance(v, str): return v.strip().lower() not in ("false", "0", "no", "off", "")
    return bool(v)


def _b(val): return "x" if _safe_bool_export(val) else ""


# ── column definitions ────────────────────────────────────────────────────────
# Each column: (header, width, attribute[, converter]).
# Header names AND order mirror the import templates generated by
# create_excel_templates.py (no STT column) – keep both in sync.
SITE_COLS = [
    ("Mien", 8, "mien"), ("Tinh", 22, "tinh"), ("Phuong xa", 22, "phuong_xa"),
    ("Site name (cu)", 22, "site_name_cu"), ("Site name", 25, "site_name"),
    ("Site VIP", 10, "site_vip"), ("Ma PTM", 14, "ma_ptm"),
    ("Lat", 14, "lat"), ("Long", 14, "long"),
    ("Tram 2G", 10, "tram_2g", _b), ("Tram 3G", 10, "tram_3g", _b),
    ("Tram 4G", 10, "tram_4g", _b), ("Tram 5G", 10, "tram_5g", _b),
    ("Repeater", 10, "repeater", _b), ("Booster", 10, "booster", _b),
    ("Node truyen dan only", 20, "node_truyen_dan_only", _b),
    ("Tram phu song TSCA", 18, "tram_phu_song_tsca", _b),
    ("Phan loai tram", 22, "phan_loai_tram"),
    ("MORAN 3G", 15, "moran_3g"), ("MORAN 4G", 15, "moran_4g"), ("MORAN 5G", 15, "moran_5g"),
    ("Do cao dinh cot anten", 22, "do_cao_dinh_cot_anten"),
    ("Do cao cot anten", 20, "do_cao_cot_anten"),
    ("Dia chi", 30, "dia_chi"), ("Ghi chu", 30, "ghi_chu"),
]

_CELL_HEAD = [
    ("Mien", 8, "mien"), ("Tinh", 22, "tinh"), ("Phuong xa", 22, "phuong_xa"),
    ("Site Name", 25, "site_name"), ("Site Name Old", 22, "site_name_old"),
    ("Cell Name", 25, "cell_name"), ("Cell Name Old", 22, "cell_name_old"),
    ("Cell VIP", 10, "cell_vip"), ("MORAN", 15, "moran"),
    ("Lat", 14, "lat"), ("Long", 14, "long"),
    ("Vung phu song", 15, "vung_phu_song"), ("Vendor", 14, "vendor"),
]
_CELL_ANTENNA = [
    ("Do cao anten", 15, "do_cao_anten"), ("Azimuth", 10, "azimuth"),
    ("M-tilt", 10, "m_tilt"), ("E-Tilt", 10, "e_tilt"),
    ("Total Tilt", 12, "total_tilt"), ("Loai Anten", 30, "loai_anten"),
]
_CHUNG_ANTEN = [("Chung anten", 18, "chung_anten")]
_CELL_TAIL = [
    ("RF", 14, "rf"), ("Cell ID", 14, "cell_id"), ("MIMO", 14, "mimo"),
    ("Cell max power (dBm)", 20, "cell_max_power"), ("BBUname", 16, "bbu_name"),
    ("Cell status (at dump time)", 24, "cell_status"),
]
_OSS = [("OSS", 14, "oss")]

CELL3G_COLS = (
    _CELL_HEAD
    + [("RNC Name", 18, "rnc_name")]
    + _CELL_ANTENNA + _CHUNG_ANTEN + _CELL_TAIL
    + [("UARFCN", 12, "uarfcn"), ("LAC", 10, "lac"), ("RAC", 10, "rac"),
       ("PSC", 10, "psc"), ("URAId", 10, "ura_id"),
       ("CPICH power (dBm)", 18, "cpich_power")]
    + _OSS
)

CELL4G_COLS = (
    _CELL_HEAD + _CELL_ANTENNA + _CHUNG_ANTEN + _CELL_TAIL
    + [("EnodeB ID", 14, "enodeb_id"), ("EARFCN", 12, "earfcn"), ("TAC", 10, "tac"),
       ("PCI", 10, "pci"), ("Root Sequence ID", 18, "root_sequence_id"),
       ("Bandwitdh", 12, "bandwidth"), ("ECI", 12, "eci")]
    + _OSS
)

CELL5G_COLS = (
    _CELL_HEAD + _CELL_ANTENNA + _CHUNG_ANTEN + _CELL_TAIL
    + [("gNodeB ID", 14, "gnodeb_id"), ("TAC", 10, "tac"), ("PCI", 10, "pci"),
       ("Root Sequence ID", 18, "root_sequence_id"),
       ("SSB-ARFCN", 12, "ssb_arfcn"), ("Center-ARFCN", 14, "center_arfcn"),
       ("GSCN", 10, "gscn"), ("Bandwidth (MHz)", 14, "bandwidth"),
       ("NCI", 12, "nci"), ("MU-MIMO", 12, "mu_mimo")]
    + _OSS
)

_SPECS: Dict[str, Dict[str, Any]] = {
    "sites": dict(
        model=Site, kind="site", cols=SITE_COLS, sheet="Sites",
        order=(Site.mien, Site.tinh, Site.site_name), filename="Sites_Export.xlsx"),
    "cells_3g": dict(
        model=Cell3G, kind="cell", cols=CELL3G_COLS, sheet="Cell_3G",
        order=(Cell3G.mien, Cell3G.tinh, Cell3G.site_name, Cell3G.cell_name),
        filename="Cells_3G_Export.xlsx"),
    "cells_4g": dict(
        model=Cell4G, kind="cell", cols=CELL4G_COLS, sheet="Cell_4G",
        order=(Cell4G.mien, Cell4G.tinh, Cell4G.site_name, Cell4G.cell_name),
        filename="Cells_4G_Export.xlsx"),
    "cells_5g": dict(
        model=Cell5G, kind="cell", cols=CELL5G_COLS, sheet="Cell_5G",
        order=(Cell5G.mien, Cell5G.tinh, Cell5G.site_name, Cell5G.cell_name),
        filename="Cells_5G_Export.xlsx"),
}

def _rows_for(key, db, params, filters, ids, sort_by, sort_dir):
    spec = _SPECS[key]
    q = build_export_query(
        db, spec["model"], spec["kind"], params,
        filters=filters, ids=ids, sort_by=sort_by, sort_dir=sort_dir,
        default_order=spec["order"],
    )
    return q.all()


def _excel(key, db, params, filters, ids, sort_by, sort_dir):
    spec = _SPECS[key]
    rows = _rows_for(key, db, params, filters, ids, sort_by, sort_dir)
    cols = spec["cols"]
    wb, ws = _make_wb([(c[0], c[1]) for c in cols])
    ws.title = spec["sheet"]
    n_cols = len(cols)
    for idx, obj in enumerate(rows, start=1):
        row = idx + 1
        for col_idx, c in enumerate(cols, start=1):
            val = getattr(obj, c[2], None)
            if len(c) > 3:
                val = c[3](val)
            ws.cell(row=row, column=col_idx, value=val)
        _style_row(ws, row, n_cols, idx % 2 == 0)
    ws.auto_filter.ref = f"A1:{get_column_letter(n_cols)}1"
    return _stream(wb, spec["filename"], len(rows))


# ── KMZ (Google Earth) – engine lives in app/services/kmz_export.py ──────────
_KMZ_MEDIA = "application/vnd.google-earth.kmz"


def _kmz_layer(layer: str) -> str:
    key = (layer or "").strip().lower().replace("-", "_")
    if key not in _SPECS:
        raise HTTPException(status_code=404, detail=f"Unknown KMZ layer '{layer}'")
    return key


def _kmz_columns(key: str):
    spec = _SPECS[key]
    return kmz_export.build_columns(spec["model"], spec["cols"])


def _kmz_response(key, db, params, filters, ids, sort_by, sort_dir, options):
    rows = _rows_for(key, db, params, filters, ids, sort_by, sort_dir)
    result = kmz_export.build_kmz(key, rows, _kmz_columns(key), options or {})
    return StreamingResponse(
        iter([result.data]),
        media_type=_KMZ_MEDIA,
        headers={
            "Content-Disposition": f'attachment; filename="{result.filename}"',
            "X-Row-Count": str(result.total),
            "X-Site-Count": str(result.total),
            "X-Valid-Coords": str(result.valid),
            "Access-Control-Expose-Headers": _EXPOSE,
        },
    )


def _kmz(db, params, filters, ids, sort_by, sort_dir):
    """Legacy /export/sites-kmz (GET/POST) -> sites with default styling options."""
    return _kmz_response("sites", db, params, filters, ids, sort_by, sort_dir, {})


# ── route registration (GET + POST for every sites / cells export) ────────────
class ExportRequest(BaseModel):
    ids:      Optional[List[int]] = None            # selected rows -> exact export
    filters:  Optional[str] = None                  # column filters (same JSON as ?filters=)
    params:   Dict[str, Any] = Field(default_factory=dict)   # top-bar filters
    sort_by:  Optional[str] = None
    sort_dir: str = "asc"


_RESERVED = {"token", "filters", "sort_by", "sort_dir", "ids"}


def _add_routes(path: str, tag: str, run: Callable[..., StreamingResponse]) -> None:
    def get_endpoint(
        request: Request,
        db: Session = Depends(get_db),
        _: User = Depends(get_optional_user),
    ):
        qp = request.query_params
        params = {k: qp.getlist(k) for k in qp.keys() if k not in _RESERVED}
        return run(db, params, qp.get("filters"), None,
                   qp.get("sort_by"), qp.get("sort_dir") or "asc")

    def post_endpoint(
        body: ExportRequest,
        db: Session = Depends(get_db),
        _: User = Depends(get_optional_user),
    ):
        return run(db, body.params, body.filters, body.ids,
                   body.sort_by, body.sort_dir)

    router.add_api_route(path, get_endpoint,  methods=["GET"],  name=f"export_{tag}_get")
    router.add_api_route(path, post_endpoint, methods=["POST"], name=f"export_{tag}_post")


_add_routes("/sites",     "sites",     partial(_excel, "sites"))
_add_routes("/cells-3g",  "cells_3g",  partial(_excel, "cells_3g"))
_add_routes("/cells-4g",  "cells_4g",  partial(_excel, "cells_4g"))
_add_routes("/cells-5g",  "cells_5g",  partial(_excel, "cells_5g"))
_add_routes("/sites-kmz", "sites_kmz", _kmz)


# ── KMZ with visualisation options (sites + cells 3G/4G/5G) ───────────────────
class KmzRequest(ExportRequest):
    options: Dict[str, Any] = Field(default_factory=dict)   # folder, color_col, icon_col, color_mode, opacity, date


@router.get("/kmz/meta/{layer}")
def kmz_meta(layer: str, _: User = Depends(get_optional_user)):
    """Columns / defaults / option labels for the KMZ dialog of a layer."""
    key = _kmz_layer(layer)
    return kmz_export.layer_meta(key, _kmz_columns(key))


@router.post("/kmz/{layer}")
def kmz_export_post(
    layer: str,
    body: KmzRequest,
    db: Session = Depends(get_db),
    _: User = Depends(get_optional_user),
):
    key = _kmz_layer(layer)
    return _kmz_response(key, db, body.params, body.filters, body.ids,
                         body.sort_by, body.sort_dir, body.options)


# ── antennas (unchanged) ──────────────────────────────────────────────────────
@router.get("/antennas")
def export_antennas(
    search:    Optional[str]  = Query(None),
    band:      Optional[str]  = Query(None),
    is_5g_aau: Optional[bool] = Query(None),
    db:        Session        = Depends(get_db),
    _:         User           = Depends(get_optional_user),
):
    q = db.query(Antenna)
    if search:    q = q.filter(Antenna.name.ilike(f"%{search}%"))
    if band:      q = q.filter(Antenna.band.ilike(f"%{band}%"))
    if is_5g_aau is not None: q = q.filter(Antenna.is_5g_aau == is_5g_aau)
    antennas = q.order_by(Antenna.name).all()
    headers = [
        ("STT", 6), ("Name", 35), ("Band", 20), ("5G AAU", 10),
        ("No of Ports", 12), ("No of Beam", 12), ("Horizontal BW", 14),
        ("Vertical BW", 12), ("Gain (dBi)", 12), ("Etilt range", 14),
        ("H (mm)", 10), ("W (mm)", 10), ("D (mm)", 10),
        ("Weight (kg)", 12), ("Connector type", 18),
        ("Spec File", 30), ("Ghi chu", 30),
    ]
    wb, ws = _make_wb(headers)
    for idx, a in enumerate(antennas, start=1):
        row = idx + 1
        values = [
            idx, a.name, a.band, "x" if a.is_5g_aau else "",
            a.no_of_ports, a.no_of_beam, a.horizontal_bw, a.vertical_bw,
            a.gain, a.etilt, a.h, a.w, a.d, a.weight, a.connector_type,
            a.spec_file_name or "", a.ghi_chu,
        ]
        for col_idx, val in enumerate(values, start=1):
            ws.cell(row=row, column=col_idx, value=val)
        _style_row(ws, row, len(headers), idx % 2 == 0)
    ws.auto_filter.ref = f"A1:{get_column_letter(len(headers))}1"
    return _stream(wb, "Antennas_Export.xlsx", len(antennas))
